# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OFEFilter
                                 A QGIS plugin
 Filtering Point Data for On-Farm Experiments
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-03
        copyright            : (C) 2024 by Sebastian Ramm
        email                : sebastian.ramm@fh-kiel.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OFEFilter class from file OFEFilter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ofe_filter import OFEFilter
    return OFEFilter(iface)
